customhost = "database-1.c54iboquj9df.us-east-1.rds.amazonaws.com"
customuser = "aws_user"
custompass = "Bait3273"
customdb = "employee"
custombucket = "limjiawei-employee"
customregion = "us-east-1"
